[tool.poetry]
name = "lightrag"
version = "0.1.0"
description = "1000 lines of code is all you need. Be light and be lightening fast."
authors = ["Li Yin <li.yin.gravity@gmail.com>"]
readme = "README.md"
include = ["lightrag", "extend", "tests", "use_cases"]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
python-dotenv = "^1.0.1"
llama-index = "^0.10.30"
faiss-cpu = "^1.8.0"
backoff = "^2.2.1"
openai = "^1.12.0"
jinja2 = "^3.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
