name: Documentation

on:
  push:
    branches:
      - xiaoyi_doc
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r ./docs/requirements.txt
          pip freeze  # Display installed packages for debugging

      - name: Sphinx build
        run: |
          # Building the documentation in the specified directory
          sphinx-build -b html docs/source/ ./docs/build/
          # Optionally, list output files for debugging
          ls -l ./docs/build/
