[tool.poetry]
name = "lightrag"

packages = [
    { include = "core", from = "." },
    { include = "components", from = "." },
    { include = "eval", from = "." },
    { include = "utils", from = "." },
    { include = "tracing", from = "." },
    { include = "optim", from = "." },
    { include = "icl", from = "." },
]
version = "0.1.0"
description = "The 'PyTorch' library for LLM applications. RAG=Retriever-Agent-Generator."
authors = ["Li Yin <li.yin.gravity@gmail.com>"]
readme = "README.md"
license = "MIT"
classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

# [[tool.poetry.packages]]
# include = "lightrag"

[tool.poetry.dependencies]
python = ">=3.11, <4.0"

python-dotenv = "^1.0.1"
backoff = "^2.2.1"
jinja2 = "^3.1.3"
jsonlines = "^4.0.0"
tiktoken = "^0.7.0"
numpy = "^1.26.4"

# TODO: decide if we need people to install faiss, or openai, or groq separatelypython = ">=3.11, <4.0"

openai = "^1.12.0"
groq = "^0.5.0"      # should only be installed if groq client is used
faiss-cpu = "^1.8.0"
# matplotlib = "^3.8.4"
# colorama = "^0.4.6"
more-itertools = "^10.3.0"


[tool.poetry.group.test.dependencies]
pytest = "^8.1.1"
pytest-mock = "^3.14.0"

[tool.poetry.group.typing.dependencies]
mypy = "^1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.7.0"


# [tool.poetry.group.doc.dependencies]
# datasets = ">=2.14.6, <=2.19.1"
# sphinx = "^7.3.7"
# sphinx-rtd-theme = "^2.0.0"
# pydata-sphinx-theme = "0.15.2"
# sphinx-design = "^0.6.0"


[tool.ruff]
exclude = ["images"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
